version: '3'
services:
  web:
    container_name: demo_backend_app
    build: .
    ports:
     - "8000:8000"
    volumes:
     - .:/app
    links:
     - db
  db:
    container_name: demo_backend_db
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: demo
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
    volumes:
      - demo_backend_volume:/var/lib/mysql

volumes:
  demo_backend_volume: